version: 2
updates:
- package-ecosystem: pip
  directory: "/backend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - python
  ignore:
  - dependency-name: fcm-django
    versions:
    - 0.3.7
    - 0.3.8
  - dependency-name: django-extensions
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.1.post1
    - 3.1.2
  - dependency-name: djangorestframework
    versions:
    - 3.12.2
    - 3.12.3
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
    - 3.1.7
  commit-message:
    prefix: Crowdbotics
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - javascript
  ignore:
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.12.18
    - 7.12.5
    - 7.13.0
    - 7.13.10
    - 7.13.16
    - 7.13.17
    - 7.13.2
    - 7.13.4
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: react-native-reanimated
    versions:
    - 1.13.2
    - 2.0.0
    - 2.0.1
  - dependency-name: react-native-gesture-handler
    versions:
    - 1.10.0
    - 1.10.1
    - 1.10.2
    - 1.9.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: react-navigation
    versions:
    - 4.4.3
  commit-message:
    prefix: Crowdbotics
