# Generated by Django 2.2.17 on 2020-11-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201109_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hfgfjfg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bjhgjgjh', models.BigIntegerField()),
            ],
        ),
    ]
